create table badgemaker_fonts (
  id bigint generated by default as identity primary key,
  name text not null,
  data_base64 text not null,
  created_at timestamptz not null default now()
);

create table badgemaker_models (
  id bigint generated by default as identity primary key,
  name text not null,
  archived boolean not null default false,
  def_rot_x numeric not null default -0.4,
  def_rot_y numeric not null default 0.2,
  def_zoom numeric not null default 1,
  bg_colour text not null default '#18181b',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table badgemaker_layers (
  id bigint generated by default as identity primary key,
  model_id bigint not null references badgemaker_models(id) on delete cascade,
  layer_order integer not null default 0,
  content text not null default 'TEXT',
  colour_hex text not null default '#e8e8e6',
  colour_id text references colours(id),
  font_id bigint references badgemaker_fonts(id),
  font_size numeric not null default 20,
  border_mm numeric not null default 0,
  thickness_mm numeric not null default 1,
  offset_x numeric not null default 0,
  offset_y numeric not null default 0,
  offset_z numeric not null default 0,
  rotation numeric not null default 0,
  created_at timestamptz not null default now()
);

alter table badgemaker_fonts enable row level security;
alter table badgemaker_models enable row level security;
alter table badgemaker_layers enable row level security;

create policy "authenticated full access" on badgemaker_fonts
  for all to authenticated using (true) with check (true);
create policy "authenticated full access" on badgemaker_models
  for all to authenticated using (true) with check (true);
create policy "authenticated full access" on badgemaker_layers
  for all to authenticated using (true) with check (true);
