create table badgemaker_inputs (
  id bigint generated by default as identity primary key,
  model_id bigint not null references badgemaker_models(id) on delete cascade,
  name text not null,
  default_value text not null default '',
  input_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table badgemaker_inputs enable row level security;

create policy "authenticated full access" on badgemaker_inputs
  for all to authenticated using (true) with check (true);

alter table badgemaker_layers add column input_id bigint references badgemaker_inputs(id) on delete set null;
